<a href="https://colab.research.google.com/github/AnantaJoy/numpy_basics/blob/main/Complete_Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import timeit


In [3]:
# version of numpy
print(np.__version__)

1.24.4


In [4]:

%timeit python_list = [i*i for i in range(100000000) ]
%timeit python_arr = np.array([i*i for i in range(10000000)])

In [ ]:
from time import process_time
start_time = process_time()
python_list = [i*i for i in range(1000000) ]
end_time = process_time()
print(f"Execution of the program {end_time - start_time}") 



Execution of the program 0.11879130200000176


In [ ]:
start = process_time()
python_arry = np.array([i*i for i in range(1000000)])
end = process_time()
print(f"Execution of the program {end - start}") 

Execution of the program 0.2241212439999991


In [ ]:

# create a random matrix with size 4x5
rng = np.random.default_rng()
python_arr = np.random.rng(20, size=(4,5))
python_arr1 = np.random.rng(5, size=10)

NameError: name 'np' is not defined

In [ ]:
# access elements
python_arr1[5:10]

array([4, 4, 3, 0, 3])

In [ ]:
# shape of an array
python_arr.shape

(4, 5)

In [ ]:
# size of array
python_arr.size

20

In [ ]:
# data type of the array
python_arr.dtype


dtype('int64')

In [ ]:
# dimension of the array
python_arr.ndim

2

In [ ]:
# size of each items
print(f"{python_arr.itemsize} bytes")

8 bytes


In [ ]:
python_arr

array([[ 0, 16,  2, 13, 19],
       [ 5,  5,  1,  4, 11],
       [ 3, 11,  6, 13, 11],
       [ 4,  1, 11,  6,  5]])

In [ ]:
python_arr[2][2]

6

In [ ]:
python_arr[:,2]

array([ 2,  1,  6, 11])

In [ ]:
python_arr[:,-1]

array([19, 11, 11,  5])

## Mathematical Operations in Numpy

In [ ]:
arr1 = np.random.randint(5, size=6)
arr2 = np.random.randint(5,size=6)
print(arr1)
print(arr2)

[3 4 4 2 0 2]
[4 1 2 1 1 4]


In [ ]:
arr1==arr2

array([False, False, False, False, False, False])

In [ ]:
# elementwise addition
arr3 = arr1+arr2
arr3

array([7, 5, 6, 3, 1, 6])

In [ ]:
# elementwise multiplication
arr4 = arr1 * arr2
print(arr4)
print(arr4.dtype)
np.sum(arr4)

[12  4  8  2  0  8]
int64


34

In [ ]:
arr_sqrt = np.sqrt(arr4)
print(arr_sqrt)
arr_sqrt.dtype


[3.46410162 2.         2.82842712 1.41421356 0.         2.82842712]


dtype('float64')

In [ ]:
# dot product of arr1 and arr2
dot_arr = np.dot(arr1, arr2)
print(dot_arr)
print(np.sum(arr4))
print(arr1@arr2)

34
34
34


In [ ]:
# inverse of a matrix
mat1 = np.random.randint(5, size=(3,3))
inverse = np.linalg.inv(mat1)
inverse

array([[ 1.11022302e-16, -8.32667268e-17,  1.00000000e+00],
       [ 4.00000000e-01, -2.00000000e-01, -1.00000000e+00],
       [-1.00000000e-01,  3.00000000e-01, -5.00000000e-01]])

In [ ]:
# determinant of a matrix
det = np.linalg.det(mat1)

In [ ]:
# diagonal of the matrix
diag = np.diag(inverse)
np.diag(diag)

array([[ 1.11022302e-16,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -2.00000000e-01,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -5.00000000e-01]])

## Slicing of an array

In [ ]:
arr_A = np.random.randint(3, size = (3,4))
arr_A

array([[2, 2, 2, 1],
       [1, 2, 2, 0],
       [2, 0, 2, 2]])

In [ ]:
arr_A[:,3]

array([1, 0, 2])

In [ ]:
arr_A[2:4]

array([[2, 0, 2, 2]])

In [ ]:
arr_A[-1,1]

0

In [ ]:
arr_A_bool  = arr_A > 0
arr_A_bool

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [ True, False,  True,  True]])

In [ ]:
# fancy indexing
a = np.random.randint(5, size=10)
b = [1,3,5,7]
print(a[b])

[2 4 4 2]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
# only even
even = np.argwhere(a%2==0).flatten()
print(a[even])

[0 2 4 2 4 2 2 4]


In [ ]:
# reshape a array
arr = np.arange(1,10)
print(arr.size)
print(arr.shape)

9
(9,)


In [ ]:
arr2 = arr.reshape(3,3)
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
print(arr.ndim)
print(arr2.ndim)

1
2


In [ ]:
# concatenate an array
a = np.random.randint(6, size=(2,3))
b = np.random.randint(3, size=(1,3))
c = np.concatenate((a,b), axis = 0)
c

array([[1, 0, 3],
       [1, 2, 3],
       [2, 1, 1]])

In [ ]:
c = np.concatenate((a,b), axis = None)
c


array([1, 0, 3, 1, 2, 3, 2, 1, 1])

In [ ]:
# c = np.concatenate((a.T,b), axis = 1)
# vstack and hstack
vstack = np.vstack((a,b))
d

array([[1, 0, 3],
       [1, 2, 3],
       [2, 1, 1]])

In [ ]:
h = np.random.randint(3, size=(2,3))
hstack = np.hstack((a,h)) 
hstack

array([[1, 0, 3, 2, 0, 2],
       [1, 2, 3, 1, 2, 1]])

## Broadcasting

In [ ]:
x = np.random.randint(10, size=(4,5))
y = np.random.randint(5, size=(1,5))
print(x)
print(y)
z = x + y 
print(z)


[[8 1 5 3 4]
 [1 6 7 2 1]
 [9 6 3 9 8]
 [0 2 2 1 4]]
[[4 4 0 3 3]]
[[12  5  5  6  7]
 [ 5 10  7  5  4]
 [13 10  3 12 11]
 [ 4  6  2  4  7]]


In [ ]:
# sum of the array
x.sum()

82

In [ ]:
x.sum(axis = 0)
x.sum(axis = 1)

array([21, 17, 35,  9])

In [ ]:
# overall mean
print(x.mean(axis = None))
print(x.mean(axis = 0))
print(x.mean(axis = 1))
# print(x.mean(axis = 2))

4.1
[4.5  3.75 4.25 3.75 4.25]
[4.2 3.4 7.  1.8]


In [ ]:
# standard deviation
print(np.std(x))
print(np.std(x, axis = 0))
print(np.std(x, axis = 1))

2.8792360097775935
[4.03112887 2.27760839 1.92028644 3.1124749  2.48746859]
[2.31516738 2.57681975 2.28035085 1.32664992]


In [ ]:
# min and max of array
print(np.min(x))
print(np.max(x))
print(np.min(x, axis = 0))
print(np.max(x, axis = 1))


0
9
[0 1 2 1 1]
[8 7 9 4]


## Datatypes

In [ ]:
array1 = np.arange(10, dtype=np.int16)
array1.dtype

dtype('int16')

In [ ]:
array2 = np.arange(10, dtype=np.float16)
array2.dtype


dtype('float16')

## Copying

In [ ]:
a = np.arange(10)
b = a.copy()
c = a
b[4] = 25
c[3] = 45
print(a)
print(b)
print(c)

[ 0  1  2 45  4  5  6  7  8  9]
[ 0  1  2  3 25  5  6  7  8  9]
[ 0  1  2 45  4  5  6  7  8  9]


## Generating array

In [ ]:
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
s = np.full((3,4), 7)
print(s)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# linspace
l = np.linspace(1,10,5)
l

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
r = np.random.random((4,5))
r.var()
r.mean()

0.5283447017763508

In [ ]:
rn = np.random.randn(100)
rn

array([ 0.0668987 ,  1.2884    ,  1.11676944,  0.55020119, -1.22628959,
        0.31406422,  0.28454833, -0.50779184,  0.37587606,  1.44275991,
       -0.6002309 , -0.72388412, -0.11114116, -0.33823256,  0.45148526,
        1.50667039,  1.15025512, -0.28038706, -1.02555197, -2.56655638,
        0.05985324,  0.11734042,  0.72806337,  0.46035377,  1.62797818,
       -1.10912595, -0.16476727,  0.48977688,  0.80307454,  0.06529226,
        0.08139337, -3.49346309, -1.20026758, -0.73980013, -0.3415933 ,
       -1.0607691 ,  0.62665057,  0.07463161,  1.62072938, -0.14565985,
        0.35726199,  2.84123952,  0.58620836, -0.1301254 ,  0.46342099,
        0.32985106, -0.17781117, -0.32563194, -2.80454685, -0.18083028,
       -0.88978344,  1.55718147, -1.05980154, -0.98328291, -1.15566938,
       -0.60693907, -0.38794095, -0.86940052,  0.1010214 ,  1.0241186 ,
        0.63594732,  1.08068687,  2.55323572,  0.31189442, -0.81023812,
       -0.18225514,  0.45579352, -0.95555648, -0.30397502,  0.58

In [ ]:
np.random.choice([3,5,7], size=(3,5))

array([[7, 3, 7, 3, 3],
       [3, 5, 5, 5, 7],
       [3, 7, 5, 3, 7]])

## Eigen Decomposition

In [ ]:
eigen = np.random.choice([3,5,7], size=(3,3))
eigenvalues, eigenvectors = np.linalg.eig(eigen)
print(eigenvalues)
print(eigenvectors)

[14.96850308 -2.21030483  0.24180175]
[[-0.58334043 -0.74037611 -0.74452089]
 [-0.64198582  0.65596089 -0.16812517]
 [-0.49756221 -0.14682821  0.64608248]]


In [ ]:
p = eigenvectors[:,0] * eigenvalues[0]
print(p)
q = eigen @ eigenvectors[:,0]
print(q)

[-8.73173306 -9.6095667  -7.44776142]
[-8.73173306 -9.6095667  -7.44776142]


In [ ]:
print(np.allclose(p,q))

True


x1 + x2 = 2200--------(i)<br>
1.5x1 + 4x2 = 5050-----(ii) 
solve the equation





In [ ]:
# solve a linear equation
A = np.array([[1,1], [1.5,4]])
b = np.array([2200,5050])
%timeit x = np.linalg.inv(A).dot(b)
%timeit y = np.linalg.solve(A, b)
print(x)
print(y)

The slowest run took 15.06 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 16.3 µs per loop
The slowest run took 10.70 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 9.06 µs per loop
[1500.  700.]
[1500.  700.]


In [ ]:
# load data in numpy array
