<a href="https://colab.research.google.com/github/AnantaJoy/numpy_basics/blob/main/Complete_Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import timeit


In [35]:
# version of numpy
print(np.__version__)

1.21.6


In [54]:

%timeit python_list = [i*i for i in range(10000) ]
%timeit python_arr = np.array([i*i for i in range(10000)])

1000 loops, best of 5: 766 µs per loop
1000 loops, best of 5: 1.42 ms per loop


In [55]:
from time import process_time
start_time = process_time()
python_list = [i*i for i in range(1000000) ]
end_time = process_time()
print(f"Execution of the program {end_time - start_time}") 



Execution of the program 0.11151411600000216


In [56]:
start = process_time()
python_arry = np.array([i*i for i in range(1000000)])
end = process_time()
print(f"Execution of the program {end - start}") 

Execution of the program 0.23319631100000038


In [57]:

# create a random matrix with size 4x5
python_arr = np.random.randint(20, size=(4,5))
python_arr1 = np.random.randint(5, size=10)

In [48]:
# access elements
python_arr1[5:10]

array([4, 4, 2, 1, 2])

In [40]:
# shape of an array
python_arr.shape

(4, 5)

In [41]:
# size of array
python_arr.size

20

In [43]:
# data type of the array
python_arr.dtype


dtype('int64')

In [44]:
# dimension of the array
python_arr.ndim

2

In [45]:
# size of each items
print(f"{python_arr.itemsize} bytes")

8 bytes


In [50]:
python_arr

array([[ 6,  9,  9, 18, 16],
       [12, 16, 18, 12, 16],
       [11,  8,  9, 11, 15],
       [ 4,  7,  3, 18, 13]])

In [49]:
python_arr[2][2]

9

In [51]:
python_arr[:,2]

array([ 9, 18,  9,  3])

In [53]:
python_arr[:,-1]

array([16, 16, 15, 13])

## Mathematical Operations in Numpy

In [63]:
arr1 = np.random.randint(5, size=6)
arr2 = np.random.randint(5,size=6)
print(arr1)
print(arr2)

[0 1 2 1 4 0]
[0 4 3 3 4 3]


In [66]:
arr1==arr2

array([ True, False, False, False,  True, False])

In [65]:
# elementwise addition
arr3 = arr1+arr2
arr3

array([0, 5, 5, 4, 8, 3])

In [79]:
# elementwise multiplication
arr4 = arr1 * arr2
print(arr4)
print(arr4.dtype)
np.sum(arr4)

[ 0  4  6  3 16  0]
int64


29

In [75]:
arr_sqrt = np.sqrt(arr4)
print(arr_sqrt)
arr_sqrt.dtype


[0.         2.         2.44948974 1.73205081 4.         0.        ]


dtype('float64')

In [80]:
# dot product of arr1 and arr2
dot_arr = np.dot(arr1, arr2)
print(dot_arr)
print(np.sum(arr4))
print(arr1@arr2)

29
29
29


In [8]:
# inverse of a matrix
mat1 = np.random.randint(5, size=(3,3))
inverse = np.linalg.inv(mat1)
inverse

array([[ 1. ,  0. , -1.5],
       [-1. ,  1. ,  0. ],
       [ 1. , -1. ,  0.5]])

In [4]:
# determinant of a matrix
det = np.linalg.det(mat1)

4.0

In [11]:
# diagonal of the matrix
diag = np.diag(inverse)
np.diag(diag)

array([[1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 0.5]])

## Slicing of an array

In [13]:
arr_A = np.random.randint(3, size = (3,4))
arr_A

array([[2, 1, 0, 2],
       [1, 0, 2, 2],
       [0, 0, 0, 1]])