# Benefits of using python:
* Speed
* Fewer loops
* Readable code
* Easy to debug
* Open Source
* Easy to use
* Larger Community
* Easy to learn

In [1]:
# NumPy: Numeric Python is a scientific computing package in Python that is used for  working with arrays. It also has functions for 
# working in domain of linear algebra, fourier transform, and matrices. NumPy was created in 2005 by Travis Oliphant. It is an open source.

# NumPy is mainly used for scientific computing in Python. It also provides a powerful N-dimensional array object, and tools for working with these arrays.

# ndarray
# N-dimensional array object
import numpy as np
arr = np.array([3,4,5,6,7])
type(arr)

numpy.ndarray

### Array 
* Data structure
* store heterogeneous data
* store data in the form of rows and columns


In [4]:
# nd array object operations
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)
print("Number of Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Item Size:", arr.itemsize)
print("Memory Address:", arr.data)

Shape: (5,)
Data Type: int64
Number of Dimensions: 1
Size: 5
Item Size: 8
Memory Address: <memory at 0x7fbad91f1540>


In [6]:
# create two dimension array

arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print(arr_2d)
print("Shape:", arr_2d.shape)
print("Data Type:", arr_2d.dtype)
print("Number of Dimensions:", arr_2d.ndim)
print("Size:", arr_2d.size)
print("Item Size:", arr_2d.itemsize)
print("Memory Address:", arr_2d.data)


[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Data Type: int64
Number of Dimensions: 2
Size: 6
Item Size: 8
Memory Address: <memory at 0x7fbae83b01e0>


In [8]:
# Numeric data types categories in numpy
import numpy as np

# Integer types
int_types = [np.int8, np.int16, np.int32, np.int64]

# Unsigned integer types
uint_types = [np.uint8, np.uint16, np.uint32, np.uint64]

# Floating-point types
float_types = [np.float16, np.float32, np.float64]

# Complex types
complex_types = [np.complex64, np.complex128]

# Boolean type
bool_type = np.bool_


# Datetime types
datetime_types = [np.datetime64]

# Timedelta types
timedelta_obj = np.timedelta64(1, 'D')


# Print the data types
print("Integer types:", int_types)
print("Unsigned integer types:", uint_types)
print("Floating-point types:", float_types)
print("Complex types:", complex_types)
print("Boolean type:", bool_type)
print("Datetime types:", datetime_types)
print("Timedelta:", timedelta_obj)


Integer types: [<class 'numpy.int8'>, <class 'numpy.int16'>, <class 'numpy.int32'>, <class 'numpy.int64'>]
Unsigned integer types: [<class 'numpy.uint8'>, <class 'numpy.uint16'>, <class 'numpy.uint32'>, <class 'numpy.uint64'>]
Floating-point types: [<class 'numpy.float16'>, <class 'numpy.float32'>, <class 'numpy.float64'>]
Complex types: [<class 'numpy.complex64'>, <class 'numpy.complex128'>]
Boolean type: <class 'numpy.bool_'>
Datetime types: [<class 'numpy.datetime64'>]
Timedelta: 1 days


In [13]:
# extended example
arr3 = np.array([9,8,7,6], dtype=np.float16)
arr3.dtype

dtype('float16')

In [16]:
date = np.array(['2008-08-28'], dtype='M')
date.dtype

dtype('<M8[D]')

In [20]:
# default function to create array

zeros = np.zeros([4,5])
ones = np.ones([3,3])
empty = np.empty([3,3])
full = np.full([4, 4], 7)
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
# create array from arange

arr4 = np.arange(10)
print(arr4)
arr5 = np.arange(1, 10, 2)
print(arr5)



[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [22]:
# create a array which are evenly spaced between two values
arr6 = np.linspace(1, 10, 4)
print(arr6)

[ 1.  4.  7. 10.]


### Slicing 

### Indexing

### Broadcasting

### Arithmetic 

### Linear Algebra

### Searching

### Sorting

### Random