<a href="https://colab.research.google.com/github/AnantaJoy/numpy_basics/blob/main/Introduction_to_Numerical_Computing_with_NumPy(Part_2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [15]:
# fancy indexing
arr = np.arange(1,15,3)
idx = np.array([1,3,-4])
fancy = arr[idx]
print(fancy) 

[ 4 10  4]


In [17]:
arr[idx] = 21
arr

array([ 1, 21,  7, 21, 13])

In [28]:
# mask a array
mask = np.random.randint(2,size=5, dtype=bool)
mask_arr = arr[mask]
print(mask_arr)

[21 13]


In [35]:
# select only  negative values using 
arr2 = np.array([-2,6,-5,-8,4,8,5])
negative = arr2<0
print(negative)
arr2[negative]

[ True False  True  True False False False]


array([-2, -5, -8])