<a href="https://colab.research.google.com/github/AnantaJoy/numpy_basics/blob/main/Introduction_to_Numerical_Computing_with_NumPy(Part_2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
# fancy indexing
arr = np.arange(1,15,3)
idx = np.array([1,3,-4])
fancy = arr[idx]
print(fancy) 

[ 4 10  4]


In [4]:
arr[idx] = 21
arr

array([ 1, 21,  7, 21, 13])

In [5]:
# mask a array
mask = np.random.randint(2,size=5, dtype=bool)
mask_arr = arr[mask]
print(mask_arr)

[ 1 21]


In [6]:
# select only  negative values using 
arr2 = np.array([-2,6,-5,-8,4,8,5])
negative = arr2<0
print(negative)
arr2[negative]

[ True False  True  True False False False]


array([-2, -5, -8])

In [7]:
arr2[negative] = 0
arr2

array([0, 6, 0, 0, 4, 8, 5])

In [28]:
arr1 = np.random.randint(10,size=(5,5))
arr1


array([[5, 1, 8, 3, 6],
       [1, 0, 9, 7, 4],
       [2, 6, 9, 2, 9],
       [8, 2, 7, 9, 4],
       [4, 3, 9, 2, 6]])

In [29]:
# access 5,4,9,2
arr1[[0,1,2,3],
       [1,2,3,4]]

array([1, 9, 2, 4])

In [30]:
# access 8,4,3 and 9,8,9
arr1[2:, [1,3]]

array([[6, 2],
       [2, 9],
       [3, 2]])

In [31]:
mask2 = np.array([0,1,0,1,1], dtype=bool)
arr1[mask2, 2]

array([9, 7, 9])

In [32]:
# number divisible by 3
mask3 = np.array(arr1%3==0)
mask3

array([[False, False, False,  True,  True],
       [False,  True,  True, False, False],
       [False,  True,  True, False,  True],
       [False, False, False,  True, False],
       [False,  True,  True, False,  True]])

In [33]:
arr1[mask3]

array([3, 6, 0, 9, 6, 9, 9, 9, 3, 9, 6])

In [34]:
arr1

array([[5, 1, 8, 3, 6],
       [1, 0, 9, 7, 4],
       [2, 6, 9, 2, 9],
       [8, 2, 7, 9, 4],
       [4, 3, 9, 2, 6]])

In [42]:
hstack = np.array([2,4,6,6,7]).reshape(5,1)
arr2 = np.hstack((arr1, hstack))
arr2

array([[5, 1, 8, 3, 6, 2],
       [1, 0, 9, 7, 4, 4],
       [2, 6, 9, 2, 9, 6],
       [8, 2, 7, 9, 4, 6],
       [4, 3, 9, 2, 6, 7]])

In [36]:
# axiswise sum
arr2.sum(axis=1).shape

(5,)

In [41]:
arr2.sum(axis=1)

array([25, 25, 34, 36, 31])

In [47]:
arr2.min()
# flatten the array show the index
arr2.argmin()

7

In [48]:
np.where(arr2 == 9)

(array([1, 2, 2, 3, 4]), array([2, 2, 4, 3, 2]))