<a href="https://colab.research.google.com/github/AnantaJoy/numpy_basics/blob/main/Introduction_to_Numerical_Computing_with_NumPy(Part_2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [15]:
# fancy indexing
arr = np.arange(1,15,3)
idx = np.array([1,3,-4])
fancy = arr[idx]
print(fancy) 

[ 4 10  4]


In [17]:
arr[idx] = 21
arr

array([ 1, 21,  7, 21, 13])

In [28]:
# mask a array
mask = np.random.randint(2,size=5, dtype=bool)
mask_arr = arr[mask]
print(mask_arr)

[21 13]


In [35]:
# select only  negative values using 
arr2 = np.array([-2,6,-5,-8,4,8,5])
negative = arr2<0
print(negative)
arr2[negative]

[ True False  True  True False False False]


array([-2, -5, -8])

In [36]:
arr2[negative] = 0
arr2

array([0, 6, 0, 0, 4, 8, 5])

In [38]:
arr1 = np.random.randint(10,size=(5,5))
arr1


array([[5, 5, 8, 0, 6],
       [9, 8, 4, 0, 7],
       [7, 8, 1, 9, 8],
       [7, 4, 9, 8, 2],
       [5, 3, 1, 9, 7]])

In [40]:
# access 5,4,9,2
arr1[[0,1,2,3],
       [1,2,3,4]]

array([5, 4, 9, 2])

In [41]:
# access 8,4,3 and 9,8,9
arr1[2:, [1,3]]

array([[8, 9],
       [4, 8],
       [3, 9]])

In [51]:
mask2 = np.array([0,1,0,1,1], dtype=bool)
arr1[mask2, 2]

array([4, 9, 1])

In [52]:
# number divisible by 3
mask3 = np.array(arr1%3==0)
mask3

array([[False, False, False,  True,  True],
       [ True, False, False,  True, False],
       [False, False, False,  True, False],
       [False, False,  True, False, False],
       [False,  True, False,  True, False]])

In [56]:
arr1[mask3]

array([0, 6, 9, 0, 9, 9, 3, 9])