## Create a virtual environment and Install Libraries

In [7]:
# Create a new virtual environment for the given directory.
# python -m venv ./(directory name)
# Install numpy packages
# pip install numpy

## Importing Libraries

In [9]:
# import numpy library as np(alias)
import numpy as np


### Creating a array

In [10]:
# create a new 1D array 
newarray = np.array([1,2,3,4,5,6,7,8])

# check if the type of the array
type(newarray)

numpy.ndarray

In [11]:
# shape of the array
np.shape(newarray)

(8,)

In [15]:
newarray + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13])

### Reshape and Swap Axes an array

In [55]:
user_age = np.array([[21,23,29,65,43,76],[65,54,34,85,51,65]])

# reshape an array to a new shape
user_age.reshape(2,2,3)

2

In [51]:
# now swap the axes
np.swapaxes(user_age, 1,1)

array([[21, 23, 29, 65, 43, 76],
       [65, 54, 34, 85, 51, 65]])

In [56]:
# dimensions in array
user_age.ndim

2

In [57]:
user_age.max()

85

In [59]:
user_age.max(axis = 0)

array([65, 54, 34, 85, 51, 76])

In [60]:
user_age.max(axis = 1)

array([76, 85])