## Create a virtual environment and Install Libraries

In [1]:
# Create a new virtual environment for the given directory.
# python -m venv ./(directory name)
# Install numpy packages
# pip install numpy

## Importing Libraries

In [2]:
# import numpy library as np(alias)
import numpy as np


### Creating a array

In [3]:
# create a new 1D array 
newarray = np.array([1,2,3,4,5,6,7,8])

# check if the type of the array
type(newarray)

numpy.ndarray

In [5]:
# shape of the array
np.shape(newarray)

(8,)

In [4]:
newarray + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [21]:
# create a zero array
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [22]:
# create a 2D array with ones
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# create a 2D array
user_age = np.array([[21,23,29,65,43,76],[65,54,34,85,51,65]])

In [17]:
user_age.shape

(2, 6)

In [20]:
user_age.ndim

2

In [32]:
# identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
# create a 2D array with linespace 
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [35]:
# array with a range of numbers
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### Reshape and Swap Axes an array

In [6]:
user_age = np.array([[21,23,29,65,43,76],[65,54,34,85,51,65]])

# reshape an array to a new shape
user_age.reshape(2,2,3)

array([[[21, 23, 29],
        [65, 43, 76]],

       [[65, 54, 34],
        [85, 51, 65]]])

In [11]:
# now swap the axes
np.swapaxes(user_age, 1,1)

array([[21, 23, 29, 65, 43, 76],
       [65, 54, 34, 85, 51, 65]])

In [9]:
# dimensions in array
user_age.ndim

2

In [10]:
user_age.max()

85

In [11]:
user_age.max(axis = 0)

array([65, 54, 34, 85, 51, 76])

In [12]:
user_age.max(axis = 1)

array([76, 85])

In [13]:
np.full((4,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [14]:
np.random.random((4,5))

array([[0.50622862, 0.3441543 , 0.66883591, 0.12764381, 0.73659417],
       [0.92887989, 0.99006063, 0.61076379, 0.18380371, 0.1156028 ],
       [0.65969102, 0.97324834, 0.06153331, 0.0982732 , 0.22236327],
       [0.47350031, 0.91906162, 0.50635392, 0.09963988, 0.613858  ]])

In [15]:
np.random.randint(1,10,(4,5))

array([[6, 1, 6, 3, 7],
       [1, 4, 7, 8, 9],
       [7, 6, 3, 2, 5],
       [5, 8, 4, 5, 4]])

In [16]:
np.random.normal(0,1,(4,5))

array([[-1.08048019, -0.92748128,  0.07952185,  0.65687523,  0.62208164],
       [-0.93176734,  2.08524746,  0.6976115 , -0.54760342,  0.67600553],
       [ 0.08019181, -0.5676982 ,  1.19321499, -2.27333731, -0.06478805],
       [-0.40383676,  1.06719742,  0.66300422,  0.04393022, -0.04135769]])

In [17]:
np.random.seed(0)

In [18]:
np.random.randint(1,10,(4,5))

array([[6, 1, 4, 4, 8],
       [4, 6, 3, 5, 8],
       [7, 9, 9, 2, 7],
       [8, 8, 9, 2, 6]])

### Why we use Numpy?

1. Numpy is faster than list
2. Numpy is more efficient than list


In [13]:
# runtime of a list comprehension
%timeit [i**2 for i in range(100000)]


29.9 ms ± 368 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [15]:
# runtime of an array
%timeit np.arange(100000)**2


741 µs ± 40.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
