In [1]:
import numpy as np
import pandas as pd
import csv
np.__version__

'1.23.1'

In [10]:
# an 1D array of 10 elements 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr2 = np.array([np.arange(40,50)])
arr + arr2

array([[41, 43, 45, 47, 49, 51, 53, 55, 57, 59]])

In [11]:
# subtract two arrays
arr2 - arr

array([[39, 39, 39, 39, 39, 39, 39, 39, 39, 39]])

In [12]:
# reshape an array
arr.reshape(2, 5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
# transpose an array
arr.reshape(2, 5).T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [2]:
import csv
with open('dataset.csv', newline='') as f:
    reader = csv.reader(f)
    data = list(reader)
print(data[11])

['9', 'MONTENEGRO, JULIETA.', 'julietamontenegro2021@gmail.com', '0', '2', '0', '2', '1,33', '3', '3', '3', '3,00', '1,67', '', '', '', '', '', '', '', '', '']


In [3]:
arr = np.array(data)
arr

array([['ID', 'Nombre', 'Mail', ..., '', '', ''],
       ['', '', '', ..., '', '', 'GRADO COMPETENCIA 3'],
       ['', '', '', ..., 'ind3', 'GRADO tpf (promedio)', ''],
       ...,
       ['202', 'PONCE, IVAN.', '', ..., '', '', ''],
       ['203', 'RODRIGUEZ, LUCIA BELEN.', '', ..., '1', '1,00', '-0,33'],
       ['204', 'ROJAS, MICAELA.', '', ..., '1', '1,00', '0,00']],
      dtype='<U39')

In [4]:
arr.shape

(202, 22)

In [5]:
arr[11,:]

array(['9', 'MONTENEGRO, JULIETA.', 'julietamontenegro2021@gmail.com',
       '0', '2', '0', '2', '1,33', '3', '3', '3', '3,00', '1,67', '', '',
       '', '', '', '', '', '', ''], dtype='<U39')

In [7]:
df = pd.read_csv('dataset.csv')
df

ID                           Nombre                          Mail  \
0      NaN                              NaN                           NaN   
1      NaN                              NaN                           NaN   
2      1.0                              NaN  altamiranoevelyn22@gmail.com   
3      2.0                              NaN         ana_chejo@hotmail.com   
4      3.0                              NaN    barbara_arroyo@outlook.com   
..     ...                              ...                           ...   
196  200.0  PALACIOS SINCHE, ANDREA JAZMIN.                           NaN   
197  201.0         PARRA, AGUSTINA SOLEDAD.                           NaN   
198  202.0                     PONCE, IVAN.                           NaN   
199  203.0          RODRIGUEZ, LUCIA BELEN.                           NaN   
200  204.0                  ROJAS, MICAELA.                           NaN   

     SIMULADOR Competencia resolucion de problemas Unnamed: 5 Unnamed: 6  \
0          NaN                         Diagnostico        NaN        NaN   
1          NaN                                ind1       ind2       ind3   
2          0.0                                   2          0          1   
3          0.0                                   4          0          4   
4          0.0                                   3          0          2   
..         ...                                 ...        ...        ...   
196        2.0                                 NaN        NaN        NaN   
197        2.0                                 NaN        NaN        NaN   
198        2.0                                 NaN        NaN        NaN   
199        2.0                                 NaN        NaN        NaN   
200        2.0                                 NaN        NaN        NaN   

                       Unnamed: 7              Unnamed: 8 Unnamed: 9  ...  \
0                             NaN  trabajo practico final        NaN  ...   
1    GRADO diagnostico (promedio)                    ind1       ind2  ...   
2                            1,00                       2          3  ...   
3                            2,67                       3          2  ...   
4                            1,67                       4          4  ...   
..                            ...                     ...        ...  ...   
196                           NaN                     NaN        NaN  ...   
197                           NaN                     NaN        NaN  ...   
198                           NaN                     NaN        NaN  ...   
199                           NaN                     NaN        NaN  ...   
200                           NaN                     NaN        NaN  ...   

             Unnamed: 12 Competencia traspolacion de habilidades Unnamed: 14  \
0    GRADO COMPETENCIA 1                             Diagnostico         NaN   
1                    NaN                                    ind1        ind2   
2                   1,67                                     NaN         NaN   
3                  -0,33                                     NaN         NaN   
4                   2,33                                     NaN         NaN   
..                   ...                                     ...         ...   
196                  NaN                                       1           3   
197                  NaN                                     NaN         NaN   
198                  NaN                                     NaN         NaN   
199                  NaN                                       1           2   
200                  NaN                                       1           1   

    Unnamed: 15                   Unnamed: 16             Unnamed: 17  \
0           NaN                           NaN  trabajo practico final   
1          ind3  GRADO diagnostico (promedio)                    ind1   
2           NaN                           NaN                    