In [1]:
# indexing rows and columns in matrix/2D array
# 2D array is a matrix
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

# accessing elements in matrix
# 1st row, 2nd column
print(a[0][1])

2


In [2]:
# slicing 2D arrays
# 2nd rows, all columns
print(a[1,:])

[4 5 6]


In [3]:
# all rows, 2nd column
print(a[:,1])

[2 5 8]


In [6]:
#  sorting in numpy

arr3 = np.array([84,36,33,82,30,92,27,20,23,24,55])
print(np.sort(arr3))

[20 23 24 27 30 33 36 55 82 84 92]


In [7]:
# filtering with fancy inexing 
# create a filter array that will return only values divided by 5
divide_of_5 = arr3 % 5 == 0
print(arr3[divide_of_5])

[30 20 55]
