`Numpy`
 >Numpy means Numerical Python. It is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices. Numpy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely. Numpy stands for Numerical Python.

* Contains only single data type 


In [4]:
# import numpy 
import numpy as np

# create a 1D array using arange function
array_1d = np.arange(10)
print(array_1d)

# create a 2D array using arange function
array_2d = np.arange(10).reshape(2,5)
print(array_2d)

# create a 3D array using arange function
array_3d = np.arange(27).reshape(3,3,3)
print(array_3d)

# create a 4D array using arange function
## ??

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [5]:
# create a arrays using zeros
array_zeros = np.zeros((3,3))

# create a arrays using random numbers
rng = np.random.default_rng()
array_random = rng.random((3,3))
print(array_random)

# create a arrays using arange
array_arange = np.arange(0,10,2)
print(array_arange)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.56246833 0.39122444 0.33879381]
 [0.39554491 0.45560085 0.35387326]
 [0.65248068 0.96117123 0.95078417]]
[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
[0 2 4 6 8]


In [6]:
# Dimension of an array 
# Vector: 1D array 
vector = np.array([1,2,3,4,5])
print(vector)

# Matrix: 2D array
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

# Tensor: 3D array
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]])
print(tensor)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]


In [11]:
# numpy data types are
# np.int64, np.float64, np.complex128, np.bool, np.object, np.string_, np.unicode_
# np.int8, np.uint8, np.int16, np.uint16, np.int32, np.uint32, np.int64, np.uint64
# np.float16, np.float32, np.float64, np.float128, np.complex64, np.complex128, np.complex256
# np.bool8, np.bool_

# create a arrays using data types
array_int = np.array([1,2,3,4,5], dtype=np.int64)
print(array_int)
print(array_int.dtype)

array_float = np.array([1.0,2.0,3.0,4.0,5.0], dtype=np.float64)
print(array_float)
print(array_float.dtype)

# using dtype as a argument
array_int = np.array([1,0,3,0,5], dtype=np.bool8)
print(array_int)
print(array_int.dtype)

#type coercion 



[1 2 3 4 5]
int64
[1. 2. 3. 4. 5.]
float64
[ True False  True False  True]
bool


In [12]:
# changing data types from one to another
arr1 = np.array([1,2,3,4,5], dtype=np.int64)
print(arr1.dtype)

arr2 = arr1.astype(np.int8)
print(arr2.dtype)

# changing from integer to bool
arr3 = arr1.astype(np.bool8)
print(arr3.dtype)

int64
int8
bool
