In [2]:
# import libraries
import numpy as np
import pandas as pd


In [4]:
# simple 1D array
arr = np.array([1, 2, 3, 4, 5])
print(type(arr))
# datatype of array
print(arr.dtype)

<class 'numpy.ndarray'>
int64


In [10]:
# create a 1D array with float datatype
arr = np.array([1, 2, 3, 4, 5], dtype='float')
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

<class 'numpy.ndarray'>
float64
1
(5,)


In [11]:
# create a 1D array with complex datatype
arr = np.array([1, 2, 3, 4, 5], dtype='complex')
print(type(arr))
print(arr.dtype)
print(arr.size)

<class 'numpy.ndarray'>
complex128
5


In [9]:
# access the data from thr array
arr[3]

4.0

In [12]:
# array operations
arr = np.array([1, 2, 3, 4, 5])
arr + 2


array([3, 4, 5, 6, 7])

In [15]:
# create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr[1][1])

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
5


In [22]:
# slicing array elements
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::-1])

# arr[start:end:step]

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[7 6 5 4 3 2 1]


In [24]:
# Universal functions(ufuncs)
arr = np.array([1, 2, 3, 4, 5])
np.sqrt(arr)


array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [25]:
# sin function
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [26]:
# log function
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [31]:
# advanced slicing of arrays
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])
print(arr[0:2, 1:4:2])
print(arr[0:2:2, 1:4:2])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]
[[2 4]
 [7 9]]
[[2 4]]


In [32]:
# reshape an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr.reshape(2, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
# flatten an array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.flatten())

[1 2 3 4 5 6 7 8]


In [37]:
# shallow and deep copy an array
# view or shallow copy
arr = np.array([1, 2, 3, 4, 5])
arr1 = arr
arr1[2] = 7
print(arr)
print(arr1)
print(id(arr))
print(id(arr1))

[1 2 7 4 5]
[1 2 7 4 5]
140711886709616
140711886709616


In [38]:
#deep copy
# copy() 
arr = np.array([1, 2, 3, 4, 5])
arr1 = arr.copy()
arr1[2] = 7
print(arr)
print(arr1)
print(id(arr))
print(id(arr1))

[1 2 3 4 5]
[1 2 7 4 5]
140711886710096
140711886709520


In [39]:
# fancy indexing
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr[[1, 3, 5]]

array([2, 4, 6])

In [45]:
# boolean indexing
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[arr > 5])
arr[np.array([True, False, True, False, True, False, True, False])]


[6 7 8]


array([1, 3, 5, 7])

In [47]:
# replacing values in an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
indices = [1,3, 5]
arr[indices] = 0
print(arr)

[1 0 3 0 5 0 7 8]


In [52]:
# fancy indexing in 2D arrays
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])
print(arr[[1, 3], [2, 4]])
print(arr[[1, 3]][:, [2, 4]])
print(arr[arr%3==0])

[ 8 20]
[[ 8 10]
 [18 20]]
[ 3  6  9 12 15 18]


In [53]:
# array concatenation
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
np.concatenate([arr1, arr2])


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
# add two arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
np.add(arr1, arr2)

array([ 7,  9, 11, 13, 15])

In [55]:
# array broadcasting
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
arr1 + arr2

array([ 7,  9, 11, 13, 15])

In [62]:
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.arange(6,11).reshape(5,1)
arr + arr2

array([[ 7,  8,  9, 10, 11],
       [ 8,  9, 10, 11, 12],
       [ 9, 10, 11, 12, 13],
       [10, 11, 12, 13, 14],
       [11, 12, 13, 14, 15]])

In [63]:
# array stacking
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
np.stack((arr1, arr2), axis=1)

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [64]:
# vstack and hstack
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [68]:
# sum of array elements axis wise
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])
print(arr.sum(axis=0))
print(arr.sum(axis=1))
print(arr.sum())
# transpose of an array
print(arr.T)


[ 7  9 11 13 15]
[15 40]
55
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [69]:
# min max value in an array
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])
print(arr.min())
print(arr.max())
print(arr.min(axis=0))
print(arr.max(axis=1))


1
10
[1 2 3 4 5]
[ 5 10]


In [77]:
# mean and median of an array
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])
print(arr.mean())
print(np.median(arr))
print(arr.mean(axis=0))
print(arr.mean(axis=1))
# print(arr.mean(axis=2))
print(arr.argmax())
print(arr.argmin())
print(arr.argmax(axis=0))
print(arr.argmax(axis=1))
print(np.unravel_index(arr.argmax(), arr.shape))

5.5
5.5
[3.5 4.5 5.5 6.5 7.5]
[3. 8.]
9
0
[1 1 1 1 1]
[4 4]
(1, 4)


In [79]:
# where function in numpy
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])
np.where(arr%2==0, 1, 0)
np.where(arr%2==0, 'T', 'F')


array([['F', 'T', 'F', 'T', 'F'],
       ['T', 'F', 'T', 'F', 'T']], dtype='<U1')

In [82]:
mask = arr%2==0
print(np.where(mask))

(array([0, 0, 1, 1, 1]), array([1, 3, 0, 2, 4]))


In [83]:
# flatten and ravel function
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])
# copy() 
arr.flatten()
# view() 
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])