In [5]:
import numpy as np
# cumulative operations
arr = np.arange(0, 12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [8]:
arr.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [13]:
# vectorized operations
arr = np.arange(1, 13).reshape(3, 4)
len(arr)

3

In [14]:
arr = np.array(['Python', 'R', 'C++', 'Java'])
len(arr) >=2 

True

In [15]:
vectorized_len = np.vectorize(len)
vectorized_len(arr) >= 2

array([ True, False,  True,  True])

In [16]:
names = np.array(['Python', 'R', 'C++', 'Java', 'C#', 'Scala', 'Julia'])
vectorized_upper = np.vectorize(str.upper)
vectorized_upper(names)

array(['PYTHON', 'R', 'C++', 'JAVA', 'C#', 'SCALA', 'JULIA'], dtype='<U6')

In [17]:
# broadcasting operations
prime = np.array([2, 3, 5, 7, 11, 13, 17, 19]).reshape(2,4)
prime+2

array([[ 4,  5,  7,  9],
       [13, 15, 19, 21]])

In [18]:
# rules of broadcasting
# 1. If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
# 2. If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
# 3. If in any dimension the sizes disagree and neither is equal to 1, an error is raised.
# shape(5,4)
# shape(1,4)
# shape(5,1)
# shape(5,4)

In [19]:
# try this array whether broadcastable or not broadcastable
# (3,5) and (4,1)
# (3,4) and (3,)

(4, 1)

In [25]:
arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(4).reshape(4,)

In [22]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
arr2

array([0, 1, 2, 3])

In [29]:
import numpy as np

array_1 = np.random.rand(3, 4)  # Shape (3, 4)
array_2 = np.random.rand(4, 1)  # Shape (4, 1)

result = array_1 + array_2

print("Array 1:")
print(array_1)
print("\nArray 2:")
print(array_2)
print("\nResult:")
print(result)


ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 